spring:
  application:
    name: client-service
  datasource:
    url: jdbc:h2:mem:testdb123
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
jwt:
  secret: KXiUPknkoVDCHdNrrYnxmA5oQLbv+LE7eHG8vkk71fjEPq0lmlZKwBhUVLUqKSmGam8P4kWxXKTGCDRgpZ5BMA==
